/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherModulesRouteImport } from './routes/teacher.modules'
import { Route as TeacherDirectoryRouteImport } from './routes/teacher.directory'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentAiRouteImport } from './routes/student.ai'
import { Route as StaffFeesRouteImport } from './routes/staff.fees'
import { Route as StaffComplaintsRouteImport } from './routes/staff.complaints'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminRecordsRouteImport } from './routes/admin.records'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as AdminOnboardRouteImport } from './routes/admin.onboard'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as TeacherModulesIndexRouteImport } from './routes/teacher.modules.index'
import { Route as AdminModulesIndexRouteImport } from './routes/admin.modules.index'
import { Route as TeacherModulesSlugRouteImport } from './routes/teacher.modules.$slug'
import { Route as AdminModulesSlugRouteImport } from './routes/admin.modules.$slug'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherModulesRoute = TeacherModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDirectoryRoute = TeacherDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiRoute = StudentAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => StudentRoute,
} as any)
const StaffFeesRoute = StaffFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StaffRoute,
} as any)
const StaffComplaintsRoute = StaffComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => StaffRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardRoute = AdminOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherModulesIndexRoute = TeacherModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherModulesRoute,
} as any)
const AdminModulesIndexRoute = AdminModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminModulesRoute,
} as any)
const TeacherModulesSlugRoute = TeacherModulesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeacherModulesRoute,
} as any)
const AdminModulesSlugRoute = AdminModulesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminModulesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/staff': typeof StaffRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/modules': typeof AdminModulesRouteWithChildren
  '/admin/onboard': typeof AdminOnboardRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/staff/complaints': typeof StaffComplaintsRoute
  '/staff/fees': typeof StaffFeesRoute
  '/student/ai': typeof StudentAiRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/fees': typeof StudentFeesRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/directory': typeof TeacherDirectoryRoute
  '/teacher/modules': typeof TeacherModulesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/modules/$slug': typeof AdminModulesSlugRoute
  '/teacher/modules/$slug': typeof TeacherModulesSlugRoute
  '/admin/modules/': typeof AdminModulesIndexRoute
  '/teacher/modules/': typeof TeacherModulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/onboard': typeof AdminOnboardRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/staff/complaints': typeof StaffComplaintsRoute
  '/staff/fees': typeof StaffFeesRoute
  '/student/ai': typeof StudentAiRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/fees': typeof StudentFeesRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/directory': typeof TeacherDirectoryRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/modules/$slug': typeof AdminModulesSlugRoute
  '/teacher/modules/$slug': typeof TeacherModulesSlugRoute
  '/admin/modules': typeof AdminModulesIndexRoute
  '/teacher/modules': typeof TeacherModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/staff': typeof StaffRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/modules': typeof AdminModulesRouteWithChildren
  '/admin/onboard': typeof AdminOnboardRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/staff/complaints': typeof StaffComplaintsRoute
  '/staff/fees': typeof StaffFeesRoute
  '/student/ai': typeof StudentAiRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/fees': typeof StudentFeesRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/directory': typeof TeacherDirectoryRoute
  '/teacher/modules': typeof TeacherModulesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/modules/$slug': typeof AdminModulesSlugRoute
  '/teacher/modules/$slug': typeof TeacherModulesSlugRoute
  '/admin/modules/': typeof AdminModulesIndexRoute
  '/teacher/modules/': typeof TeacherModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/register'
    | '/sign-in'
    | '/staff'
    | '/student'
    | '/teacher'
    | '/admin/admissions'
    | '/admin/ai'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/modules'
    | '/admin/onboard'
    | '/admin/people'
    | '/admin/records'
    | '/admin/staff'
    | '/staff/complaints'
    | '/staff/fees'
    | '/student/ai'
    | '/student/attendance'
    | '/student/fees'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/directory'
    | '/teacher/modules'
    | '/admin/'
    | '/staff/'
    | '/student/'
    | '/teacher/'
    | '/admin/modules/$slug'
    | '/teacher/modules/$slug'
    | '/admin/modules/'
    | '/teacher/modules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/sign-in'
    | '/admin/admissions'
    | '/admin/ai'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/onboard'
    | '/admin/people'
    | '/admin/records'
    | '/admin/staff'
    | '/staff/complaints'
    | '/staff/fees'
    | '/student/ai'
    | '/student/attendance'
    | '/student/fees'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/directory'
    | '/admin'
    | '/staff'
    | '/student'
    | '/teacher'
    | '/admin/modules/$slug'
    | '/teacher/modules/$slug'
    | '/admin/modules'
    | '/teacher/modules'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/register'
    | '/sign-in'
    | '/staff'
    | '/student'
    | '/teacher'
    | '/admin/admissions'
    | '/admin/ai'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/modules'
    | '/admin/onboard'
    | '/admin/people'
    | '/admin/records'
    | '/admin/staff'
    | '/staff/complaints'
    | '/staff/fees'
    | '/student/ai'
    | '/student/attendance'
    | '/student/fees'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/directory'
    | '/teacher/modules'
    | '/admin/'
    | '/staff/'
    | '/student/'
    | '/teacher/'
    | '/admin/modules/$slug'
    | '/teacher/modules/$slug'
    | '/admin/modules/'
    | '/teacher/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
  StaffRoute: typeof StaffRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/modules': {
      id: '/teacher/modules'
      path: '/modules'
      fullPath: '/teacher/modules'
      preLoaderRoute: typeof TeacherModulesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/directory': {
      id: '/teacher/directory'
      path: '/directory'
      fullPath: '/teacher/directory'
      preLoaderRoute: typeof TeacherDirectoryRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai': {
      id: '/student/ai'
      path: '/ai'
      fullPath: '/student/ai'
      preLoaderRoute: typeof StudentAiRouteImport
      parentRoute: typeof StudentRoute
    }
    '/staff/fees': {
      id: '/staff/fees'
      path: '/fees'
      fullPath: '/staff/fees'
      preLoaderRoute: typeof StaffFeesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/complaints': {
      id: '/staff/complaints'
      path: '/complaints'
      fullPath: '/staff/complaints'
      preLoaderRoute: typeof StaffComplaintsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboard': {
      id: '/admin/onboard'
      path: '/onboard'
      fullPath: '/admin/onboard'
      preLoaderRoute: typeof AdminOnboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/modules/': {
      id: '/teacher/modules/'
      path: '/'
      fullPath: '/teacher/modules/'
      preLoaderRoute: typeof TeacherModulesIndexRouteImport
      parentRoute: typeof TeacherModulesRoute
    }
    '/admin/modules/': {
      id: '/admin/modules/'
      path: '/'
      fullPath: '/admin/modules/'
      preLoaderRoute: typeof AdminModulesIndexRouteImport
      parentRoute: typeof AdminModulesRoute
    }
    '/teacher/modules/$slug': {
      id: '/teacher/modules/$slug'
      path: '/$slug'
      fullPath: '/teacher/modules/$slug'
      preLoaderRoute: typeof TeacherModulesSlugRouteImport
      parentRoute: typeof TeacherModulesRoute
    }
    '/admin/modules/$slug': {
      id: '/admin/modules/$slug'
      path: '/$slug'
      fullPath: '/admin/modules/$slug'
      preLoaderRoute: typeof AdminModulesSlugRouteImport
      parentRoute: typeof AdminModulesRoute
    }
  }
}

interface AdminModulesRouteChildren {
  AdminModulesSlugRoute: typeof AdminModulesSlugRoute
  AdminModulesIndexRoute: typeof AdminModulesIndexRoute
}

const AdminModulesRouteChildren: AdminModulesRouteChildren = {
  AdminModulesSlugRoute: AdminModulesSlugRoute,
  AdminModulesIndexRoute: AdminModulesIndexRoute,
}

const AdminModulesRouteWithChildren = AdminModulesRoute._addFileChildren(
  AdminModulesRouteChildren,
)

interface AdminRouteChildren {
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminModulesRoute: typeof AdminModulesRouteWithChildren
  AdminOnboardRoute: typeof AdminOnboardRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminAiRoute: AdminAiRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminModulesRoute: AdminModulesRouteWithChildren,
  AdminOnboardRoute: AdminOnboardRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffRouteChildren {
  StaffComplaintsRoute: typeof StaffComplaintsRoute
  StaffFeesRoute: typeof StaffFeesRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffComplaintsRoute: StaffComplaintsRoute,
  StaffFeesRoute: StaffFeesRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface StudentRouteChildren {
  StudentAiRoute: typeof StudentAiRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAiRoute: StudentAiRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherModulesRouteChildren {
  TeacherModulesSlugRoute: typeof TeacherModulesSlugRoute
  TeacherModulesIndexRoute: typeof TeacherModulesIndexRoute
}

const TeacherModulesRouteChildren: TeacherModulesRouteChildren = {
  TeacherModulesSlugRoute: TeacherModulesSlugRoute,
  TeacherModulesIndexRoute: TeacherModulesIndexRoute,
}

const TeacherModulesRouteWithChildren = TeacherModulesRoute._addFileChildren(
  TeacherModulesRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherClassesRoute: typeof TeacherClassesRoute
  TeacherDirectoryRoute: typeof TeacherDirectoryRoute
  TeacherModulesRoute: typeof TeacherModulesRouteWithChildren
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherClassesRoute: TeacherClassesRoute,
  TeacherDirectoryRoute: TeacherDirectoryRoute,
  TeacherModulesRoute: TeacherModulesRouteWithChildren,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
  StaffRoute: StaffRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
